version: '3'
services:
  web:
    build: .
    ports:
      - "5003:5003"
    volumes:
      - ./:/app
    networks:
      - app-network
  mongo:
    image: mongo
    ports:
      - "2018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongodb-data:
